export enum AppointmentType {
  GENERAL = "GENERAL",
  FOLLOW_UP = "FOLLOW_UP",
  URGENT = "URGENT",
  ROUTINE_CHECKUP = "ROUTINE_CHECKUP",
  SPECIALIST = "SPECIALIST",
  TELECONSULTATION = "TELECONSULTATION",
}
