export enum ReportType {
  APPOINTMENT_STATS = "APPOINTMENT_STATS",
  PATIENT_DEMOGRAPHICS = "PATIENT_DEMOGRAPHICS",
  MEDICAL_CONDITIONS = "MEDICAL_CONDITIONS",
  DOCTOR_PRODUCTIVITY = "DOCTOR_PRODUCTIVITY",
  REVENUE_REPORT = "REVENUE_REPORT",
  MEDICAL_AUDIT = "MEDICAL_AUDIT",
  PATIENT_SATISFACTION = "PATIENT_SATISFACTION",
  OPERATIONAL_METRICS = "OPERATIONAL_METRICS",
  NO_SHOW_ANALYSIS = "NO_SHOW_ANALYSIS",
}
