export enum FollowUpType {
  LAB_TEST = "LAB_TEST",
  IMAGING_STUDY = "IMAGING_STUDY",
  SPECIALIST_VISIT = "SPECIALIST_VISIT",
  MEDICATION_REVIEW = "MEDICATION_REVIEW",
  SYMPTOM_MONITORING = "SYMPTOM_MONITORING",
  VACCINATION = "VACCINATION",
  PHYSICAL_THERAPY = "PHYSICAL_THERAPY",
  NUTRITION_CONSULT = "NUTRITION_CONSULT",
  PSYCHOLOGICAL_EVALUATION = "PSYCHOLOGICAL_EVALUATION",
  GENERAL_CHECKUP = "GENERAL_CHECKUP",
}
